### ISSUE TITLE
There is an error when I running the src in the PHP8.1

### ISSUE THREAD

**Issue by orangeZSCB** [SDLYYZ/Tangokoto#24]
`syntax error, unexpected token ":" in /home/$USRNAME/TangokotoAPITest/index.php on line 6`
There is a new error when i annotated this line:
```
Uncaught TypeError: sizeof(): Argument # 1 ($value) must be of type Countable|array, bool given in /home/$USRNAME/TangokotoAPITest/index.php: line 4
```
When i annotated every error line, it just returned back 3 Chinese words.
Very weird
By the way, when is the teapot(lyoi.cc) becomes cannot visit again? I wanna use Tangokoto API, but there's a 503 error when i use this API. 

**Tips: please test your code in PHP8.1! Because maybe it is a new version's bug, or the new version has removed old attributes.**

_Ad: OrangeOJ (main):http://oj.zsccodelnc.cn:11451 (Shenzhen Node): http://oj2.zsccodelnc.cn:19198 (Shiyan Node): https://oj3.zsccodelnc.cn:41118 (maybe not safe, but it is my website, right?) Status page: https://zsccodelnc.cn/status/oj_

**Comment by DeCalvin2006** [comment]
See <https://www.php.net/manual/zh/function.file.php>
![image](https://github.com/SDLYYZ/Tangokoto/assets/54260142/b39a6cd2-8d72-468d-bd6c-5bd47c0e5acc)
请检查是否在目录下有`Tangokoto.txt`。
另：附带log时请用代码块，不然会比较费眼

**Comment by orangeZSCB** [comment]
我已经放了Tangokoto.txt，不然程序就不会有返回了。
“当我注释了所有的错误行之后，只返回了三个汉字”，那三个汉字我懒得去丢到工具里解码了。
很显然，错误的行是6，错误信息是`syntax error, unexpected token ":" in /home/$USRNAME/TangokotoAPITest/index.php on line 6`，就是这个冒号出了问题（（（（
我不知道怎么改（因为我怎么改都会错）（（（（
如果我没有记错的话，应该是行4、5、6都出了错。
（那可能就是tangokoto这个数组出了问题了（（（（（（（（（（（
复现步骤：
系统：Ubuntu 22.04 LTS
1. 进入sudo，`sudo su`
2. 运行`apt install php`
3. 进入到源代码所在文件`cd /home/$USERNAME/TangokotoAPI`（内包含了Tangokoto.php index.php）
4. 运行`php index.php`以测试
5. 出现错误。

我保证在复现过程内代码我一点没动，并且已经放置了Tangokoto.txt

（虽然我用Python复刻完了TangokotoAPI，在这里... http://oj2.zsccodelnc.cn:22890/get_tangokoto）

**Comment by qwqFranzFox** [comment]
> 我已经放了Tangokoto.txt，不然程序就不会有返回了。 “当我注释了所有的错误行之后，只返回了三个汉字”，那三个汉字我懒得去丢到工具里解码了。 很显然，错误的行是6，错误信息是`syntax error, unexpected token ":" in /home/$USRNAME/TangokotoAPITest/index.php on line 6`，就是这个冒号出了问题（（（（ 我不知道怎么改（因为我怎么改都会错）（（（（ 如果我没有记错的话，应该是行4、5、6都出了错。 （那可能就是tangokoto这个数组出了问题了（（（（（（（（（（（ 复现步骤： 系统：Ubuntu 22.04 LTS
> 
> 1. 进入sudo，`sudo su`
> 2. 运行`apt install php`
> 3. 进入到源代码所在文件`cd /home/$USERNAME/TangokotoAPI`（内包含了Tangokoto.php index.php）
> 4. 运行`php index.php`以测试
> 5. 出现错误。
> 
> 我保证在复现过程内代码我一点没动，并且已经放置了Tangokoto.txt
> 
> （虽然我用Python复刻完了TangokotoAPI，在这里... [http://oj2.zsccodelnc.cn:22890/get_tangokoto）](http://oj2.zsccodelnc.cn:22890/get_tangokoto%EF%BC%89)

我的疏忽。
第6行的括号并不配对，因而三元表达式不完整爆出SyntaxError。
然而，文件读取部分也有错误。通配符行为似乎不正常，`**/Tangokoto.txt`改成`./Tangokoto.txt`后运行`php src/Tangokoto.php`就可以了

**Comment by orangeZSCB** [comment]
So can u just fix it and create a pr?

Although i don't use it anymore, but we can't let other people have this same issue.
